name: analysis_options_cli_generator
version: 1.0.0
description: A starting point for Dart libraries or applications.
environment: 
  sdk: '>=2.14.0 <3.0.0'
dependencies: 
  dcli: ^1.8.0
dev_dependencies: 
  lints: ^1.0.0
  test: ^1.16.0
